# Stage 1: Build with Maven and Java 21
FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Stage 2: Run the Spring Boot JAR
FROM eclipse-temurin:21-jdk
WORKDIR /app
# Copy the built JAR from the Maven build stage
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080
# Run the JAR
ENTRYPOINT ["java","-jar","app.jar"]
